import React from "react";
// Define the data structure matching your backend
const CATALOG = [

  {
    "id": "samsung-s24-ultra",
    "name": "Samsung Galaxy S24 Ultra",
    "brand": "Samsung",
    "priceInr": 129999,
    "os": "Android 14 (One UI)",
    "soc": "Snapdragon 8 Gen 3",
    "ramGB": 12,
    "storageGB": 512,
    "display": { "sizeInches": 6.8, "type": "Dynamic AMOLED", "refreshHz": 120, "resolution": "1440x3120" },
    "batteryMah": 5000,
    "chargingWatt": 45,
    "cameras": { "mainMP": 200, "ultraMP": 12, "teleMP": 50, "ois": true, "eis": true, "selfieMP": 12 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 162.3, "width": 79.0, "thickness": 8.6, "weight": 232 },
    "release": "2024",
    "tags": ["flagship", "camera", "s-pen"],
    "scores": { "camera": 9.8, "battery": 9.0, "performance": 9.8, "display": 9.7, "value": 8.5 },
    "image": "/img/s24ultra.jpg",
    "url": "https://www.samsung.com"
  },
  {
    "id": "iphone-15-pro",
    "name": "Apple iPhone 15 Pro",
    "brand": "Apple",
    "priceInr": 134900,
    "os": "iOS 17",
    "soc": "A17 Pro",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.1, "type": "Super Retina XDR", "refreshHz": 120, "resolution": "1179x2556" },
    "batteryMah": 3274,
    "chargingWatt": 20,
    "cameras": { "mainMP": 48, "ultraMP": 12, "teleMP": 12, "ois": true, "eis": true, "selfieMP": 12 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 146.6, "width": 70.6, "thickness": 8.3, "weight": 187 },
    "release": "2023",
    "tags": ["flagship", "camera", "premium"],
    "scores": { "camera": 9.6, "battery": 7.8, "performance": 9.9, "display": 9.5, "value": 7.8 },
    "image": "/img/iphone15pro.jpg",
    "url": "https://www.apple.com"
  },
  {
    "id": "oneplus-12",
    "name": "OnePlus 12",
    "brand": "OnePlus",
    "priceInr": 64999,
    "os": "Android 14 (OxygenOS)",
    "soc": "Snapdragon 8 Gen 3",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 6.82, "type": "AMOLED", "refreshHz": 120, "resolution": "1440x3168" },
    "batteryMah": 5400,
    "chargingWatt": 100,
    "cameras": { "mainMP": 50, "ultraMP": 48, "teleMP": 64, "ois": true, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP65" },
    "dims": { "height": 164.3, "width": 75.8, "thickness": 9.2, "weight": 220 },
    "release": "2024",
    "tags": ["flagship", "performance", "fast-charging"],
    "scores": { "camera": 9.2, "battery": 9.5, "performance": 9.7, "display": 9.4, "value": 8.8 },
    "image": "/img/op12.jpg",
    "url": "https://www.oneplus.in"
  },
  {
    "id": "xiaomi-14",
    "name": "Xiaomi 14",
    "brand": "Xiaomi",
    "priceInr": 69999,
    "os": "Android 14 (HyperOS)",
    "soc": "Snapdragon 8 Gen 3",
    "ramGB": 12,
    "storageGB": 512,
    "display": { "sizeInches": 6.36, "type": "AMOLED", "refreshHz": 120, "resolution": "1200x2670" },
    "batteryMah": 4610,
    "chargingWatt": 90,
    "cameras": { "mainMP": 50, "ultraMP": 50, "teleMP": 50, "ois": true, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 152.8, "width": 71.5, "thickness": 8.2, "weight": 193 },
    "release": "2024",
    "tags": ["flagship", "camera", "compact"],
    "scores": { "camera": 9.4, "battery": 8.2, "performance": 9.6, "display": 9.3, "value": 8.2 },
    "image": "/img/xiaomi14.jpg",
    "url": "https://www.mi.com"
  },
  {
    "id": "google-pixel-8-pro",
    "name": "Google Pixel 8 Pro",
    "brand": "Google",
    "priceInr": 106999,
    "os": "Android 14 (Pixel UI)",
    "soc": "Tensor G3",
    "ramGB": 12,
    "storageGB": 128,
    "display": { "sizeInches": 6.7, "type": "OLED", "refreshHz": 120, "resolution": "1344x2992" },
    "batteryMah": 5050,
    "chargingWatt": 30,
    "cameras": { "mainMP": 50, "ultraMP": 48, "teleMP": 48, "ois": true, "eis": true, "selfieMP": 10.5 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 162.6, "width": 76.5, "thickness": 8.8, "weight": 213 },
    "release": "2023",
    "tags": ["camera", "ai", "stock-android"],
    "scores": { "camera": 9.7, "battery": 8.0, "performance": 8.8, "display": 9.2, "value": 7.9 },
    "image": "/img/pixel8pro.jpg",
    "url": "https://store.google.com"
  },
  {
    "id": "samsung-s24-plus",
    "name": "Samsung Galaxy S24+",
    "brand": "Samsung",
    "priceInr": 99999,
    "os": "Android 14 (One UI)",
    "soc": "Snapdragon 8 Gen 3",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 6.7, "type": "Dynamic AMOLED", "refreshHz": 120, "resolution": "1440x3088" },
    "batteryMah": 4900,
    "chargingWatt": 45,
    "cameras": { "mainMP": 50, "ultraMP": 12, "teleMP": 10, "ois": true, "eis": true, "selfieMP": 12 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 158.5, "width": 75.9, "thickness": 7.7, "weight": 197 },
    "release": "2024",
    "tags": ["flagship", "balanced", "premium"],
    "scores": { "camera": 9.1, "battery": 8.8, "performance": 9.5, "display": 9.4, "value": 8.2 },
    "image": "/img/s24plus.jpg",
    "url": "https://www.samsung.com"
  },
  {
    "id": "iphone-15",
    "name": "Apple iPhone 15",
    "brand": "Apple",
    "priceInr": 79900,
    "os": "iOS 17",
    "soc": "A16 Bionic",
    "ramGB": 6,
    "storageGB": 128,
    "display": { "sizeInches": 6.1, "type": "Super Retina XDR", "refreshHz": 60, "resolution": "1179x2556" },
    "batteryMah": 3349,
    "chargingWatt": 20,
    "cameras": { "mainMP": 48, "ultraMP": 12, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 12 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 147.6, "width": 71.6, "thickness": 7.8, "weight": 171 },
    "release": "2023",
    "tags": ["premium", "camera", "ios"],
    "scores": { "camera": 8.8, "battery": 7.5, "performance": 9.2, "display": 8.5, "value": 7.2 },
    "image": "/img/iphone15.jpg",
    "url": "https://www.apple.com"
  },
  {
    "id": "oneplus-nord-4",
    "name": "OnePlus Nord 4",
    "brand": "OnePlus",
    "priceInr": 29999,
    "os": "Android 14 (OxygenOS)",
    "soc": "Snapdragon 7+ Gen 3",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.74, "type": "AMOLED", "refreshHz": 120, "resolution": "1240x2772" },
    "batteryMah": 5500,
    "chargingWatt": 100,
    "cameras": { "mainMP": 50, "ultraMP": 8, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP65" },
    "dims": { "height": 162.9, "width": 75.3, "thickness": 8.4, "weight": 192 },
    "release": "2024",
    "tags": ["performance", "charging", "value"],
    "scores": { "camera": 8.3, "battery": 9.1, "performance": 8.9, "display": 8.6, "value": 9.2 },
    "image": "/img/nord4.jpg",
    "url": "https://www.oneplus.in"
  },
  {
    "id": "realme-gt-6t",
    "name": "Realme GT 6T",
    "brand": "Realme",
    "priceInr": 30999,
    "os": "Android 14 (Realme UI)",
    "soc": "Snapdragon 7+ Gen 3",
    "ramGB": 8,
    "storageGB": 256,
    "display": { "sizeInches": 6.78, "type": "AMOLED", "refreshHz": 120, "resolution": "1264x2780" },
    "batteryMah": 5500,
    "chargingWatt": 120,
    "cameras": { "mainMP": 50, "ultraMP": 8, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP65" },
    "dims": { "height": 162.0, "width": 75.1, "thickness": 8.7, "weight": 191 },
    "release": "2024",
    "tags": ["performance", "gaming", "fast-charging"],
    "scores": { "camera": 8.4, "battery": 9.3, "performance": 9.1, "display": 8.7, "value": 9.0 },
    "image": "/img/realamegt6t.jpg",
    "url": "https://www.realme.com"
  },
  {
    "id": "poco-f6",
    "name": "Poco F6",
    "brand": "Poco",
    "priceInr": 27999,
    "os": "Android 14 (HyperOS)",
    "soc": "Snapdragon 8s Gen 3",
    "ramGB": 8,
    "storageGB": 256,
    "display": { "sizeInches": 6.67, "type": "AMOLED", "refreshHz": 120, "resolution": "1220x2712" },
    "batteryMah": 5000,
    "chargingWatt": 90,
    "cameras": { "mainMP": 50, "ultraMP": 8, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 20 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP64" },
    "dims": { "height": 160.5, "width": 74.4, "thickness": 8.1, "weight": 179 },
    "release": "2024",
    "tags": ["performance", "gaming", "value"],
    "scores": { "camera": 8.1, "battery": 8.6, "performance": 9.3, "display": 8.5, "value": 9.3 },
    "image": "/img/pocof6.jpg",
    "url": "https://www.poco.in"
  },
  {
    "id": "vivo-v30-pro",
    "name": "Vivo V30 Pro",
    "brand": "Vivo",
    "priceInr": 42999,
    "os": "Android 14 (Funtouch)",
    "soc": "Dimensity 8200",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 6.78, "type": "AMOLED", "refreshHz": 120, "resolution": "1260x2800" },
    "batteryMah": 5000,
    "chargingWatt": 80,
    "cameras": { "mainMP": 50, "ultraMP": 50, "teleMP": 50, "ois": true, "eis": true, "selfieMP": 50 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 164.4, "width": 75.1, "thickness": 7.5, "weight": 188 },
    "release": "2024",
    "tags": ["camera", "portrait", "premium"],
    "scores": { "camera": 9.0, "battery": 8.4, "performance": 8.7, "display": 9.0, "value": 8.3 },
    "image": "/img/vivov30pro.jpg",
    "url": "https://www.vivo.com"
  },
  {
    "id": "moto-edge-50-pro",
    "name": "Moto Edge 50 Pro",
    "brand": "Motorola",
    "priceInr": 34999,
    "os": "Android 14 (MyUX)",
    "soc": "Snapdragon 7 Gen 3",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 6.7, "type": "pOLED", "refreshHz": 144, "resolution": "1220x2712" },
    "batteryMah": 4500,
    "chargingWatt": 125,
    "cameras": { "mainMP": 50, "ultraMP": 13, "teleMP": 10, "ois": true, "eis": true, "selfieMP": 50 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 161.2, "width": 72.4, "thickness": 8.2, "weight": 186 },
    "release": "2024",
    "tags": ["display", "charging", "clean-ui"],
    "scores": { "camera": 8.6, "battery": 8.2, "performance": 8.5, "display": 9.1, "value": 8.6 },
    "image": "/img/motoedge50pro.jpg",
    "url": "https://www.motorola.in"
  },
  {
    "id": "iqoo-neo-9-pro",
    "name": "iQOO Neo 9 Pro",
    "brand": "iQOO",
    "priceInr": 35999,
    "os": "Android 14 (Funtouch)",
    "soc": "Dimensity 9300",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 6.78, "type": "AMOLED", "refreshHz": 144, "resolution": "1260x2800" },
    "batteryMah": 5160,
    "chargingWatt": 120,
    "cameras": { "mainMP": 50, "ultraMP": 50, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP54" },
    "dims": { "height": 163.5, "width": 75.8, "thickness": 8.3, "weight": 196 },
    "release": "2024",
    "tags": ["gaming", "performance", "fast-charging"],
    "scores": { "camera": 8.7, "battery": 8.9, "performance": 9.6, "display": 8.9, "value": 9.1 },
    "image": "/img/iqooneo9pro.jpg",
    "url": "https://www.iqoo.com"
  },
  {
    "id": "nothing-phone-2",
    "name": "Nothing Phone (2)",
    "brand": "Nothing",
    "priceInr": 44999,
    "os": "Android 14 (Nothing OS)",
    "soc": "Snapdragon 8+ Gen 1",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 6.7, "type": "AMOLED", "refreshHz": 120, "resolution": "1080x2412" },
    "batteryMah": 4700,
    "chargingWatt": 45,
    "cameras": { "mainMP": 50, "ultraMP": 50, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP54" },
    "dims": { "height": 161.1, "width": 76.4, "thickness": 8.6, "weight": 201 },
    "release": "2023",
    "tags": ["design", "unique", "glyph"],
    "scores": { "camera": 8.3, "battery": 8.0, "performance": 8.8, "display": 8.5, "value": 8.2 },
    "image": "/img/nothing2.jpg",
    "url": "https://in.nothing.tech"
  },
  {
    "id": "samsung-a55",
    "name": "Samsung Galaxy A55",
    "brand": "Samsung",
    "priceInr": 34999,
    "os": "Android 14 (One UI)",
    "soc": "Exynos 1480",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.6, "type": "Super AMOLED", "refreshHz": 120, "resolution": "1080x2340" },
    "batteryMah": 5000,
    "chargingWatt": 25,
    "cameras": { "mainMP": 50, "ultraMP": 12, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP67" },
    "dims": { "height": 161.1, "width": 77.4, "thickness": 8.2, "weight": 213 },
    "release": "2024",
    "tags": ["mid-range", "samsung", "balanced"],
    "scores": { "camera": 8.1, "battery": 8.5, "performance": 8.2, "display": 8.3, "value": 8.4 },
    "image": "/img/a55.jpg",
    "url": "https://www.samsung.com"
  },
  {
    "id": "redmi-note-13",
    "name": "Redmi Note 13",
    "brand": "Xiaomi",
    "priceInr": 17999,
    "os": "Android 14 (HyperOS)",
    "soc": "Snapdragon 685",
    "ramGB": 6,
    "storageGB": 128,
    "display": { "sizeInches": 6.67, "type": "AMOLED", "refreshHz": 120, "resolution": "1080x2400" },
    "batteryMah": 5000,
    "chargingWatt": 33,
    "cameras": { "mainMP": 108, "ultraMP": 8, "teleMP": 2, "ois": false, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP54" },
    "dims": { "height": 161.1, "width": 75.0, "thickness": 7.6, "weight": 173 },
    "release": "2024",
    "tags": ["value", "camera", "budget"],
    "scores": { "camera": 8.0, "battery": 8.3, "performance": 7.2, "display": 8.2, "value": 8.8 },
    "image": "/img/redminote13.jpg",
    "url": "https://www.mi.com"
  },
  {
    "id": "realme-11-pro-plus",
    "name": "Realme 11 Pro+",
    "brand": "Realme",
    "priceInr": 27999,
    "os": "Android 14 (Realme UI)",
    "soc": "Dimensity 7050",
    "ramGB": 8,
    "storageGB": 256,
    "display": { "sizeInches": 6.7, "type": "AMOLED", "refreshHz": 120, "resolution": "1080x2412" },
    "batteryMah": 5000,
    "chargingWatt": 100,
    "cameras": { "mainMP": 200, "ultraMP": 8, "teleMP": 2, "ois": true, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 161.6, "width": 73.9, "thickness": 8.2, "weight": 183 },
    "release": "2023",
    "tags": ["camera", "design", "charging"],
    "scores": { "camera": 8.5, "battery": 8.4, "performance": 7.8, "display": 8.3, "value": 8.6 },
    "image": "/img/realme11proplus.jpg",
    "url": "https://www.realme.com"
  },
  {
    "id": "poco-m6-pro",
    "name": "Poco M6 Pro",
    "brand": "Poco",
    "priceInr": 12999,
    "os": "Android 14 (HyperOS)",
    "soc": "Snapdragon 4 Gen 2",
    "ramGB": 6,
    "storageGB": 128,
    "display": { "sizeInches": 6.79, "type": "IPS LCD", "refreshHz": 90, "resolution": "1080x2460" },
    "batteryMah": 5000,
    "chargingWatt": 18,
    "cameras": { "mainMP": 50, "ultraMP": 2, "teleMP": 0, "ois": false, "eis": true, "selfieMP": 8 },
    "features": { "fiveG": true, "nfc": false, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 168.6, "width": 76.3, "thickness": 8.2, "weight": 205 },
    "release": "2024",
    "tags": ["budget", "battery", "value"],
    "scores": { "camera": 7.0, "battery": 8.5, "performance": 6.5, "display": 7.2, "value": 8.9 },
    "image": "/img/pocom6pro.jpg",
    "url": "https://www.poco.in"
  },
  {
    "id": "vivo-t2-pro",
    "name": "Vivo T2 Pro",
    "brand": "Vivo",
    "priceInr": 23999,
    "os": "Android 14 (Funtouch)",
    "soc": "Dimensity 7200",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.78, "type": "AMOLED", "refreshHz": 120, "resolution": "1080x2400" },
    "batteryMah": 4600,
    "chargingWatt": 66,
    "cameras": { "mainMP": 64, "ultraMP": 8, "teleMP": 2, "ois": false, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 164.1, "width": 74.9, "thickness": 7.4, "weight": 171 },
    "release": "2023",
    "tags": ["performance", "slim", "value"],
    "scores": { "camera": 7.8, "battery": 7.8, "performance": 8.3, "display": 8.1, "value": 8.7 },
    "image": "/img/vivot2pro.jpg",
    "url": "https://www.vivo.com"
  },
  {
    "id": "moto-g84",
    "name": "Moto G84",
    "brand": "Motorola",
    "priceInr": 16999,
    "os": "Android 14 (MyUX)",
    "soc": "Snapdragon 695",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 6.5, "type": "pOLED", "refreshHz": 120, "resolution": "1080x2400" },
    "batteryMah": 5000,
    "chargingWatt": 30,
    "cameras": { "mainMP": 50, "ultraMP": 8, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP52" },
    "dims": { "height": 160.0, "width": 74.4, "thickness": 7.6, "weight": 167 },
    "release": "2023",
    "tags": ["value", "clean-ui", "balanced"],
    "scores": { "camera": 7.5, "battery": 8.2, "performance": 7.4, "display": 7.9, "value": 8.8 },
    "image": "/img/motog84.jpg",
    "url": "https://www.motorola.in"
  },
  {
    "id": "oppo-reno-11",
    "name": "Oppo Reno 11",
    "brand": "Oppo",
    "priceInr": 29999,
    "os": "Android 14 (ColorOS)",
    "soc": "Dimensity 7050",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.7, "type": "AMOLED", "refreshHz": 120, "resolution": "1080x2412" },
    "batteryMah": 5000,
    "chargingWatt": 67,
    "cameras": { "mainMP": 50, "ultraMP": 8, "teleMP": 32, "ois": true, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP54" },
    "dims": { "height": 162.4, "width": 74.3, "thickness": 7.6, "weight": 182 },
    "release": "2024",
    "tags": ["camera", "design", "portrait"],
    "scores": { "camera": 8.4, "battery": 8.3, "performance": 7.9, "display": 8.4, "value": 8.5 },
    "image": "/img/opporeno11.jpg",
    "url": "https://www.oppo.com"
  },
  {
    "id": "tecno-camon-20",
    "name": "Tecno Camon 20",
    "brand": "Tecno",
    "priceInr": 11999,
    "os": "Android 14 (HIOS)",
    "soc": "Helio G85",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.67, "type": "IPS LCD", "refreshHz": 120, "resolution": "1080x2400" },
    "batteryMah": 5000,
    "chargingWatt": 18,
    "cameras": { "mainMP": 64, "ultraMP": 2, "teleMP": 0, "ois": false, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": false, "nfc": false, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 164.4, "width": 76.1, "thickness": 8.4, "weight": 190 },
    "release": "2023",
    "tags": ["budget", "camera", "value"],
    "scores": { "camera": 7.3, "battery": 8.1, "performance": 6.8, "display": 7.1, "value": 8.6 },
    "image": "/img/tecnocamon20.jpg",
    "url": "https://www.tecno-mobile.in"
  },
  {
    "id": "infinix-zero-30",
    "name": "Infinix Zero 30",
    "brand": "Infinix",
    "priceInr": 21999,
    "os": "Android 14 (XOS)",
    "soc": "Dimensity 8020",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 6.78, "type": "AMOLED", "refreshHz": 144, "resolution": "1080x2400" },
    "batteryMah": 5000,
    "chargingWatt": 68,
    "cameras": { "mainMP": 108, "ultraMP": 13, "teleMP": 2, "ois": true, "eis": true, "selfieMP": 50 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 164.5, "width": 74.5, "thickness": 7.9, "weight": 185 },
    "release": "2023",
    "tags": ["value", "camera", "performance"],
    "scores": { "camera": 8.2, "battery": 8.4, "performance": 8.1, "display": 8.3, "value": 8.9 },
    "image": "/img/infinixzero30.jpg",
    "url": "https://www.infinixmobility.com"
  },
  {
    "id": "lava-blaze-2",
    "name": "Lava Blaze 2",
    "brand": "Lava",
    "priceInr": 7999,
    "os": "Android 13",
    "soc": "Unisoc T616",
    "ramGB": 4,
    "storageGB": 64,
    "display": { "sizeInches": 6.5, "type": "IPS LCD", "refreshHz": 90, "resolution": "720x1600" },
    "batteryMah": 5000,
    "chargingWatt": 18,
    "cameras": { "mainMP": 50, "ultraMP": 2, "teleMP": 0, "ois": false, "eis": true, "selfieMP": 8 },
    "features": { "fiveG": false, "nfc": false, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 164.7, "width": 76.0, "thickness": 8.6, "weight": 203 },
    "release": "2023",
    "tags": ["budget", "made-in-india"],
    "scores": { "camera": 6.5, "battery": 8.0, "performance": 5.8, "display": 6.5, "value": 8.2 },
    "image": "/img/lavablaze2.jpg",
    "url": "https://www.lavamobiles.com"
  },
  {
    "id": "nokia-g42",
    "name": "Nokia G42",
    "brand": "Nokia",
    "priceInr": 10999,
    "os": "Android 13",
    "soc": "Snapdragon 480+",
    "ramGB": 4,
    "storageGB": 128,
    "display": { "sizeInches": 6.56, "type": "IPS LCD", "refreshHz": 90, "resolution": "720x1612" },
    "batteryMah": 5000,
    "chargingWatt": 20,
    "cameras": { "mainMP": 50, "ultraMP": 2, "teleMP": 0, "ois": false, "eis": true, "selfieMP": 8 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP52" },
    "dims": { "height": 165.0, "width": 75.8, "thickness": 8.6, "weight": 194 },
    "release": "2023",
    "tags": ["budget", "reliable", "repairable"],
    "scores": { "camera": 6.8, "battery": 8.1, "performance": 6.2, "display": 6.8, "value": 8.0 },
    "image": "/img/nokiag42.jpg",
    "url": "https://www.nokia.com"
  },
  {
    "id": "asus-rog-phone-8",
    "name": "Asus ROG Phone 8",
    "brand": "Asus",
    "priceInr": 89999,
    "os": "Android 14 (ROG UI)",
    "soc": "Snapdragon 8 Gen 3",
    "ramGB": 16,
    "storageGB": 512,
    "display": { "sizeInches": 6.78, "type": "AMOLED", "refreshHz": 165, "resolution": "1080x2448" },
    "batteryMah": 5500,
    "chargingWatt": 65,
    "cameras": { "mainMP": 50, "ultraMP": 13, "teleMP": 32, "ois": true, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 163.8, "width": 76.8, "thickness": 8.9, "weight": 225 },
    "release": "2024",
    "tags": ["gaming", "performance", "flagship"],
    "scores": { "camera": 8.8, "battery": 9.2, "performance": 9.9, "display": 9.3, "value": 8.0 },
    "image": "/img/rogphone8.jpg",
    "url": "https://www.asus.com"
  },
  {
    "id": "sony-xperia-1-v",
    "name": "Sony Xperia 1 V",
    "brand": "Sony",
    "priceInr": 99999,
    "os": "Android 14",
    "soc": "Snapdragon 8 Gen 2",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 6.5, "type": "OLED", "refreshHz": 120, "resolution": "1644x3840" },
    "batteryMah": 5000,
    "chargingWatt": 30,
    "cameras": { "mainMP": 48, "ultraMP": 12, "teleMP": 12, "ois": true, "eis": true, "selfieMP": 12 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 165.0, "width": 71.0, "thickness": 8.3, "weight": 187 },
    "release": "2023",
    "tags": ["camera", "pro", "display"],
    "scores": { "camera": 9.5, "battery": 8.0, "performance": 9.0, "display": 9.6, "value": 7.5 },
    "image": "/img/xperia1v.jpg",
    "url": "https://www.sony.co.in"
  },
  {
    "id": "honor-magic-6-pro",
    "name": "Honor Magic 6 Pro",
    "brand": "Honor",
    "priceInr": 79999,
    "os": "Android 14 (Magic UI)",
    "soc": "Snapdragon 8 Gen 3",
    "ramGB": 12,
    "storageGB": 512,
    "display": { "sizeInches": 6.8, "type": "OLED", "refreshHz": 120, "resolution": "1280x2800" },
    "batteryMah": 5600,
    "chargingWatt": 80,
    "cameras": { "mainMP": 50, "ultraMP": 50, "teleMP": 180, "ois": true, "eis": true, "selfieMP": 50 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 162.5, "width": 75.8, "thickness": 8.9, "weight": 225 },
    "release": "2024",
    "tags": ["flagship", "camera", "innovative"],
    "scores": { "camera": 9.3, "battery": 9.4, "performance": 9.5, "display": 9.2, "value": 8.3 },
    "image": "/img/honormagic6pro.jpg",
    "url": "https://www.hihonor.com"
  },
  {
    "id": "apple-iphone-se-4",
    "name": "Apple iPhone SE (4th Gen)",
    "brand": "Apple",
    "priceInr": 44900,
    "os": "iOS 17",
    "soc": "A16 Bionic",
    "ramGB": 4,
    "storageGB": 128,
    "display": { "sizeInches": 6.1, "type": "Retina HD", "refreshHz": 60, "resolution": "828x1792" },
    "batteryMah": 3279,
    "chargingWatt": 20,
    "cameras": { "mainMP": 48, "ultraMP": 0, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 12 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP67" },
    "dims": { "height": 146.7, "width": 71.5, "thickness": 7.8, "weight": 144 },
    "release": "2024",
    "tags": ["compact", "ios", "value"],
    "scores": { "camera": 8.2, "battery": 7.0, "performance": 9.0, "display": 7.5, "value": 7.8 },
    "image": "/img/iphonese4.jpg",
    "url": "https://www.apple.com"
  },
  {
    "id": "google-pixel-7a",
    "name": "Google Pixel 7a",
    "brand": "Google",
    "priceInr": 43999,
    "os": "Android 14 (Pixel UI)",
    "soc": "Tensor G2",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.1, "type": "OLED", "refreshHz": 90, "resolution": "1080x2400" },
    "batteryMah": 4385,
    "chargingWatt": 18,
    "cameras": { "mainMP": 64, "ultraMP": 13, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 13 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP67" },
    "dims": { "height": 152.4, "width": 72.9, "thickness": 9.0, "weight": 193 },
    "release": "2023",
    "tags": ["camera", "compact", "stock-android"],
    "scores": { "camera": 9.0, "battery": 7.0, "performance": 7.8, "display": 8.2, "value": 8.0 },
    "image": "/img/pixel7a.jpg",
    "url": "https://store.google.com"
  },
  {
    "id": "oneplus-11r",
    "name": "OnePlus 11R",
    "brand": "OnePlus",
    "priceInr": 39999,
    "os": "Android 14 (OxygenOS)",
    "soc": "Snapdragon 8+ Gen 1",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.74, "type": "AMOLED", "refreshHz": 120, "resolution": "1240x2772" },
    "batteryMah": 5000,
    "chargingWatt": 100,
    "cameras": { "mainMP": 50, "ultraMP": 8, "teleMP": 2, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 163.4, "width": 74.3, "thickness": 8.7, "weight": 204 },
    "release": "2023",
    "tags": ["performance", "value", "fast-charging"],
    "scores": { "camera": 8.3, "battery": 8.8, "performance": 9.2, "display": 8.8, "value": 9.0 },
    "image": "/img/op11r.jpg",
    "url": "https://www.oneplus.in"
  },
  {
    "id": "samsung-z-fold-5",
    "name": "Samsung Galaxy Z Fold 5",
    "brand": "Samsung",
    "priceInr": 154999,
    "os": "Android 14 (One UI)",
    "soc": "Snapdragon 8 Gen 2",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 7.6, "type": "Dynamic AMOLED", "refreshHz": 120, "resolution": "1812x2176" },
    "batteryMah": 4400,
    "chargingWatt": 25,
    "cameras": { "mainMP": 50, "ultraMP": 12, "teleMP": 10, "ois": true, "eis": true, "selfieMP": 10 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IPX8" },
    "dims": { "height": 129.9, "width": 154.9, "thickness": 6.1, "weight": 253 },
    "release": "2023",
    "tags": ["foldable", "premium", "productivity"],
    "scores": { "camera": 9.0, "battery": 7.8, "performance": 9.3, "display": 9.5, "value": 7.0 },
    "image": "/img/zfold5.jpg",
    "url": "https://www.samsung.com"
  },
  {
    "id": "samsung-z-flip-5",
    "name": "Samsung Galaxy Z Flip 5",
    "brand": "Samsung",
    "priceInr": 99999,
    "os": "Android 14 (One UI)",
    "soc": "Snapdragon 8 Gen 2",
    "ramGB": 8,
    "storageGB": 256,
    "display": { "sizeInches": 6.7, "type": "Dynamic AMOLED", "refreshHz": 120, "resolution": "1080x2640" },
    "batteryMah": 3700,
    "chargingWatt": 25,
    "cameras": { "mainMP": 12, "ultraMP": 12, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 10 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IPX8" },
    "dims": { "height": 165.1, "width": 71.9, "thickness": 6.9, "weight": 187 },
    "release": "2023",
    "tags": ["foldable", "compact", "style"],
    "scores": { "camera": 8.0, "battery": 6.8, "performance": 8.8, "display": 8.7, "value": 7.2 },
    "image": "/img/zflip5.jpg",
    "url": "https://www.samsung.com"
  },
  {
    "id": "motorola-razr-40-ultra",
    "name": "Motorola Razr 40 Ultra",
    "brand": "Motorola",
    "priceInr": 89999,
    "os": "Android 13 (MyUX)",
    "soc": "Snapdragon 8+ Gen 1",
    "ramGB": 8,
    "storageGB": 256,
    "display": { "sizeInches": 6.9, "type": "pOLED", "refreshHz": 165, "resolution": "1080x2640" },
    "batteryMah": 3800,
    "chargingWatt": 30,
    "cameras": { "mainMP": 12, "ultraMP": 13, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP52" },
    "dims": { "height": 170.8, "width": 74.0, "thickness": 7.0, "weight": 188 },
    "release": "2023",
    "tags": ["foldable", "nostalgia", "compact"],
    "scores": { "camera": 7.8, "battery": 6.9, "performance": 8.5, "display": 8.9, "value": 7.5 },
    "image": "/img/motorolarazr40ultra.jpg",
    "url": "https://www.motorola.in"
  },
  {
    "id": "xiaomi-13t-pro",
    "name": "Xiaomi 13T Pro",
    "brand": "Xiaomi",
    "priceInr": 59999,
    "os": "Android 14 (HyperOS)",
    "soc": "Dimensity 9200+",
    "ramGB": 12,
    "storageGB": 512,
    "display": { "sizeInches": 6.67, "type": "AMOLED", "refreshHz": 144, "resolution": "1220x2712" },
    "batteryMah": 5000,
    "chargingWatt": 120,
    "cameras": { "mainMP": 50, "ultraMP": 50, "teleMP": 50, "ois": true, "eis": true, "selfieMP": 20 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP68" },
    "dims": { "height": 162.2, "width": 75.7, "thickness": 8.5, "weight": 206 },
    "release": "2023",
    "tags": ["camera", "performance", "fast-charging"],
    "scores": { "camera": 9.1, "battery": 8.7, "performance": 9.4, "display": 8.9, "value": 8.4 },
    "image": "/img/xiaomi13tpro.jpg",
    "url": "https://www.mi.com"
  },
  {
    "id": "realme-gt-neo-5",
    "name": "Realme GT Neo 5",
    "brand": "Realme",
    "priceInr": 35999,
    "os": "Android 14 (Realme UI)",
    "soc": "Snapdragon 8+ Gen 1",
    "ramGB": 12,
    "storageGB": 256,
    "display": { "sizeInches": 6.74, "type": "AMOLED", "refreshHz": 144, "resolution": "1240x2772" },
    "batteryMah": 4600,
    "chargingWatt": 240,
    "cameras": { "mainMP": 50, "ultraMP": 8, "teleMP": 2, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 163.9, "width": 75.8, "thickness": 8.9, "weight": 199 },
    "release": "2023",
    "tags": ["fast-charging", "performance", "gaming"],
    "scores": { "camera": 8.5, "battery": 8.3, "performance": 9.3, "display": 8.8, "value": 8.9 },
    "image": "/img/realmegtneo5.jpg",
    "url": "https://www.realme.com"
  },
  {
    "id": "nubia-red-magic-9-pro",
    "name": "Nubia Red Magic 9 Pro",
    "brand": "Nubia",
    "priceInr": 64999,
    "os": "Android 14 (Redmagic OS)",
    "soc": "Snapdragon 8 Gen 3",
    "ramGB": 16,
    "storageGB": 512,
    "display": { "sizeInches": 6.8, "type": "AMOLED", "refreshHz": 165, "resolution": "1116x2480" },
    "batteryMah": 6500,
    "chargingWatt": 80,
    "cameras": { "mainMP": 50, "ultraMP": 50, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 164.0, "width": 76.4, "thickness": 8.9, "weight": 229 },
    "release": "2023",
    "tags": ["gaming", "performance", "cooling"],
    "scores": { "camera": 8.2, "battery": 9.6, "performance": 9.8, "display": 9.1, "value": 8.7 },
    "image": "/img/redmagic9pro.jpg",
    "url": "https://www.redmagic.gg"
  },
  {
    "id": "black-shark-5-pro",
    "name": "Black Shark 5 Pro",
    "brand": "Black Shark",
    "priceInr": 59999,
    "os": "Android 12 (Joy UI)",
    "soc": "Snapdragon 8 Gen 1",
    "ramGB": 16,
    "storageGB": 512,
    "display": { "sizeInches": 6.67, "type": "AMOLED", "refreshHz": 144, "resolution": "1080x2400" },
    "batteryMah": 4650,
    "chargingWatt": 120,
    "cameras": { "mainMP": 108, "ultraMP": 13, "teleMP": 5, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 163.8, "width": 76.5, "thickness": 9.5, "weight": 220 },
    "release": "2022",
    "tags": ["gaming", "performance", "accessories"],
    "scores": { "camera": 8.0, "battery": 8.1, "performance": 9.2, "display": 8.7, "value": 8.3 },
    "image": "/img/blackshark5pro.jpg",
    "url": "https://www.blackshark.com"
  }
];

export default CATALOG;