import React from "react";
// Define the data structure matching your backend
const CATALOG = [
  {
    "id": "pixel-8a",
    "name": "Google Pixel 8a",
    "brand": "Google",
    "priceInr": 52999,
    "os": "Android 14 (Pixel UI)",
    "soc": "Tensor G3",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.1, "type": "OLED", "refreshHz": 120, "resolution": "1080x2400" },
    "batteryMah": 4492,
    "chargingWatt": 18,
    "cameras": { "mainMP": 64, "ultraMP": 13, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 13 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP67" },
    "dims": { "height": 152.1, "width": 72.7, "thickness": 8.9, "weight": 188 },
    "release": "2024",
    "tags": ["camera", "compact", "stock-android"],
    "scores": { "camera": 9.4, "battery": 7.2, "performance": 8.0, "display": 8.7, "value": 7.5 },
    "image": "/img/pixel8a.jpg",
    "url": "https://store.google.com"
  },
  {
    "id": "oneplus-12r",
    "name": "OnePlus 12R",
    "brand": "OnePlus",
    "priceInr": 39999,
    "os": "Android 14 (OxygenOS)",
    "soc": "Snapdragon 8 Gen 2",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.78, "type": "AMOLED", "refreshHz": 120, "resolution": "1264x2780" },
    "batteryMah": 5500,
    "chargingWatt": 100,
    "cameras": { "mainMP": 50, "ultraMP": 8, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP64" },
    "dims": { "height": 163.3, "width": 75.3, "thickness": 8.8, "weight": 207 },
    "release": "2024",
    "tags": ["performance", "battery", "fast-charging"],
    "scores": { "camera": 8.2, "battery": 9.2, "performance": 9.5, "display": 9.0, "value": 8.8 },
    "image": "/img/op12r.jpg",
    "url": "https://www.oneplus.in"
  },
  {
    "id": "redmi-note-13-pro-plus",
    "name": "Redmi Note 13 Pro+",
    "brand": "Xiaomi",
    "priceInr": 29999,
    "os": "Android 14 (HyperOS)",
    "soc": "Dimensity 7200-Ultra",
    "ramGB": 8,
    "storageGB": 256,
    "display": { "sizeInches": 6.67, "type": "AMOLED", "refreshHz": 120, "resolution": "1220x2712" },
    "batteryMah": 5000,
    "chargingWatt": 120,
    "cameras": { "mainMP": 200, "ultraMP": 8, "teleMP": 2, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP68" },
    "dims": { "height": 161.4, "width": 74.2, "thickness": 8.9, "weight": 204 },
    "release": "2024",
    "tags": ["camera", "fast-charging", "value"],
    "scores": { "camera": 8.7, "battery": 8.7, "performance": 8.1, "display": 8.6, "value": 9.0 },
    "image": "/img/rn13pplus.jpg",
    "url": "https://www.mi.com"
  },
  {
    "id": "poco-x6-pro",
    "name": "Poco X6 Pro",
    "brand": "Poco",
    "priceInr": 26999,
    "os": "Android 14 (HyperOS)",
    "soc": "Dimensity 8300-Ultra",
    "ramGB": 8,
    "storageGB": 256,
    "display": { "sizeInches": 6.67, "type": "AMOLED", "refreshHz": 120, "resolution": "1220x2712" },
    "batteryMah": 5000,
    "chargingWatt": 67,
    "cameras": { "mainMP": 64, "ultraMP": 8, "teleMP": 2, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP54" },
    "dims": { "height": 160.5, "width": 74.3, "thickness": 8.3, "weight": 186 },
    "release": "2024",
    "tags": ["performance", "gaming", "value"],
    "scores": { "camera": 7.8, "battery": 8.3, "performance": 9.2, "display": 8.5, "value": 9.1 },
    "image": "/img/pocox6pro.jpg",
    "url": "https://www.poco.in"
  },
  {
    "id": "iqoo-z9",
    "name": "iQOO Z9",
    "brand": "iQOO",
    "priceInr": 19999,
    "os": "Android 14 (Funtouch)",
    "soc": "Dimensity 7200",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.67, "type": "AMOLED", "refreshHz": 120, "resolution": "1080x2400" },
    "batteryMah": 5000,
    "chargingWatt": 44,
    "cameras": { "mainMP": 50, "ultraMP": 2, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": false, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 164.6, "width": 75.7, "thickness": 7.8, "weight": 188 },
    "release": "2024",
    "tags": ["value", "camera"],
    "scores": { "camera": 8.1, "battery": 8.0, "performance": 8.2, "display": 8.1, "value": 9.2 },
    "image": "/img/iqooz9.jpg",
    "url": "https://www.iqoo.com"
  },
  {
    "id": "nothing-phone-2a",
    "name": "Nothing Phone (2a)",
    "brand": "Nothing",
    "priceInr": 23999,
    "os": "Android 14 (Nothing OS)",
    "soc": "Dimensity 7200 Pro",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.7, "type": "AMOLED", "refreshHz": 120, "resolution": "1080x2412" },
    "batteryMah": 5000,
    "chargingWatt": 45,
    "cameras": { "mainMP": 50, "ultraMP": 50, "teleMP": 0, "ois": false, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP54" },
    "dims": { "height": 161.7, "width": 76.3, "thickness": 8.6, "weight": 190 },
    "release": "2024",
    "tags": ["design", "value"],
    "scores": { "camera": 7.9, "battery": 8.1, "performance": 8.0, "display": 8.2, "value": 8.8 },
    "image": "/img/nothing2a.jpg",
    "url": "https://in.nothing.tech"
  },
  {
    "id": "samsung-a15",
    "name": "Samsung Galaxy A15 5G",
    "brand": "Samsung",
    "priceInr": 14999,
    "os": "Android 14 (One UI)",
    "soc": "Dimensity 6100+",
    "ramGB": 6,
    "storageGB": 128,
    "display": { "sizeInches": 6.5, "type": "Super AMOLED", "refreshHz": 90, "resolution": "1080x2340" },
    "batteryMah": 5000,
    "chargingWatt": 25,
    "cameras": { "mainMP": 50, "ultraMP": 5, "teleMP": 0, "ois": false, "eis": true, "selfieMP": 13 },
    "features": { "fiveG": true, "nfc": false, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 160.1, "width": 76.8, "thickness": 8.4, "weight": 200 },
    "release": "2024",
    "tags": ["budget", "battery"],
    "scores": { "camera": 7.2, "battery": 8.2, "performance": 6.8, "display": 7.8, "value": 8.5 },
    "image": "/img/a15.jpg",
    "url": "https://www.samsung.com"
  },
  {
    "id": "samsung-s23-fe",
    "name": "Samsung Galaxy S23 FE",
    "brand": "Samsung",
    "priceInr": 49999,
    "os": "Android 14 (One UI)",
    "soc": "Exynos 2200",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.4, "type": "Dynamic AMOLED", "refreshHz": 120, "resolution": "1080x2340" },
    "batteryMah": 4500,
    "chargingWatt": 25,
    "cameras": { "mainMP": 50, "ultraMP": 12, "teleMP": 8, "ois": true, "eis": true, "selfieMP": 10 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": true, "ipRating": "IP68" },
    "dims": { "height": 158.0, "width": 76.5, "thickness": 8.2, "weight": 209 },
    "release": "2023",
    "tags": ["camera", "extras", "compact"],
    "scores": { "camera": 8.6, "battery": 7.6, "performance": 8.5, "display": 8.8, "value": 7.6 },
    "image": "/img/s23fe.jpg",
    "url": "https://www.samsung.com"
  },
  {
    "id": "moto-edge-50-fusion",
    "name": "Moto Edge 50 Fusion",
    "brand": "Motorola",
    "priceInr": 25999,
    "os": "Android 14 (MyUX)",
    "soc": "Snapdragon 7s Gen 2",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.7, "type": "pOLED", "refreshHz": 144, "resolution": "1080x2400" },
    "batteryMah": 5000,
    "chargingWatt": 68,
    "cameras": { "mainMP": 50, "ultraMP": 13, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 32 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP68" },
    "dims": { "height": 161.9, "width": 73.6, "thickness": 7.9, "weight": 174 },
    "release": "2024",
    "tags": ["display", "clean-ui", "value"],
    "scores": { "camera": 8.0, "battery": 8.4, "performance": 8.0, "display": 9.0, "value": 8.9 },
    "image": "/img/motoedge50fusion.jpg",
    "url": "https://www.motorola.in"
  },
  {
    "id": "realme-narzo-70-pro",
    "name": "Realme Narzo 70 Pro",
    "brand": "Realme",
    "priceInr": 18999,
    "os": "Android 14 (Realme UI)",
    "soc": "Dimensity 7050",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.67, "type": "AMOLED", "refreshHz": 120, "resolution": "1080x2400" },
    "batteryMah": 5000,
    "chargingWatt": 67,
    "cameras": { "mainMP": 50, "ultraMP": 8, "teleMP": 2, "ois": false, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": false, "wirelessCharging": false, "ipRating": "IP54" },
    "dims": { "height": 162.6, "width": 75.4, "thickness": 8.1, "weight": 190 },
    "release": "2024",
    "tags": ["value", "charging"],
    "scores": { "camera": 7.6, "battery": 8.3, "performance": 7.8, "display": 8.2, "value": 8.9 },
    "image": "/img/narzo70pro.jpg",
    "url": "https://www.realme.com"
  },
  {
    "id": "oneplus-nord-ce4",
    "name": "OnePlus Nord CE 4",
    "brand": "OnePlus",
    "priceInr": 24999,
    "os": "Android 14 (OxygenOS)",
    "soc": "Snapdragon 7 Gen 3",
    "ramGB": 8,
    "storageGB": 128,
    "display": { "sizeInches": 6.7, "type": "AMOLED", "refreshHz": 120, "resolution": "1080x2412" },
    "batteryMah": 5500,
    "chargingWatt": 100,
    "cameras": { "mainMP": 50, "ultraMP": 8, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 16 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "" },
    "dims": { "height": 162.5, "width": 75.2, "thickness": 8.5, "weight": 186 },
    "release": "2024",
    "tags": ["battery", "charging", "value"],
    "scores": { "camera": 8.0, "battery": 9.0, "performance": 8.7, "display": 8.4, "value": 9.0 },
    "image": "/img/nordce4.jpg",
    "url": "https://www.oneplus.in"
  },
  {
    "id": "vivo-v30",
    "name": "Vivo V30",
    "brand": "Vivo",
    "priceInr": 32999,
    "os": "Android 14 (Funtouch)",
    "soc": "Snapdragon 7 Gen 3",
    "ramGB": 8,
    "storageGB": 256,
    "display": { "sizeInches": 6.78, "type": "AMOLED", "refreshHz": 120, "resolution": "1260x2800" },
    "batteryMah": 5000,
    "chargingWatt": 80,
    "cameras": { "mainMP": 50, "ultraMP": 50, "teleMP": 0, "ois": true, "eis": true, "selfieMP": 50 },
    "features": { "fiveG": true, "nfc": true, "wirelessCharging": false, "ipRating": "IP54" },
    "dims": { "height": 164.4, "width": 75.1, "thickness": 7.5, "weight": 186 },
    "release": "2024",
    "tags": ["camera", "portrait"],
    "scores": { "camera": 8.5, "battery": 8.3, "performance": 8.5, "display": 8.9, "value": 8.1 },
    "image": "/img/vivov30.jpg",
    "url": "https://www.vivo.com"
  }
];

export default CATALOG;